---
- name: Turing Pi Cluster Information
  hosts: turing_cluster
  gather_facts: true

  tasks:
    - name: Display hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Display operating system
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Display architecture
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}"

    - name: Display processor core count
      ansible.builtin.debug:
        msg: "CPU cores: {{ ansible_processor_vcpus }}"

    - name: Display total memory
      ansible.builtin.debug:
        msg: "Memor: {{ ansible_memtotal_mb }} MB"