---
- name: Turing Pi Cluster Information
  hosts: turing_cluster
  gather_facts: true

  tasks:
    - name: Display hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"