[control_plane]
# turing-node01 will be added here when the replacement module arrives

[workers]
turing-node02 ansible_host=192.168.8.111
turing-node03 ansible_host=192.168.8.128
turing-node04 ansible_host=192.168.8.203
turing-node05 ansible_host=192.168.8.144
turing-node06 ansible_host=192.168.8.228
turing-node07 ansible_host=192.168.8.194

[turing_cluster:children]
control_plane
workers

[turing_cluster:vars]
ansible_user=piadmin
ansible_python_interpreter=/usr/bin/python3
