[turing_cluster]
turing-node01 ansible_connection=local
turing-node02
turing-node03
turing-node04
turing-node05
turing-node06
turing-node07


[turing_cluster:vars]
ansible_python_interpreter=/usr/bin/python3.13