---
- name: Ansible Loops Lab
  hosts: turing_cluster
  become: true

  tasks:
    - name: Create cluster test files
      ansible.builtin.file:
        path: "/tmp/ {{ item }}"
        state: touch
        node: "0644"
      loop: 
        - loop-test-1.txt
        - loop-test-2.txt
        - loop-test-3.txt