---
- name: Ansible Loops Lab
  hosts: turing_cluster
  become: true

  tasks:
    - name: Create cluster test files
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: touch
        mode: "0644"
      loop:
        - loop-test-1.txt
        - loop-test-2.txt
        - loop-test-3.txt

    - name: Create cluster info files
      ansible.builtin.copy:
        dest: "/tmp/{{ item.filename }}"
        content: "{{ item.content }}"
        mode: "0644"
      loop:
        - filename: node-role.txt
          content: "Role: {{ node_role }}"
        - filename: node-location.txt
          content: "Location: {{ node_location }}"

    # - name: Ensure useful packages are installed
    #   ansible.builtin.apt:
    #     name: "{{ item }}"
    #     state: present
    #     update_cache: false
    #   loop:
    #     - htop
    #     - curl
    #     - git

    - name: Check installed software versions
      ansible.builtin.command: "{{ item }}"
      register: software_versions #Added this to actually see the versions.. Needed to add the following task
      changed_when: false
      loop:
        - "docker --version"
        - "python3 --version"

    - name: Display installed software versions
      ansible.builtin.debug:
        msg: "{{ item.stdout }}"
      loop: "{{ software_versions.results }}"
      loop_control: #Added this to make the results more cleaner
        label: " {{ item.item }}" #Added this to make the results more cleaner

    - name: Remove loop lab temporary files
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - loop-test-1.txt
        - loop-test-2.txt
        - loop-test-3.txt
        - node-role.txt
        - node-location.txt